# Done to increase the memory available to gradle.
org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true

org.gradle.configuration-cache = false

# Fabric Properties (matched to create-fly-26.2-rc-2-6.0.9-1-FA-fix.jar)
minecraft_version               = 26.2-rc-2
loader_version                  = 0.19.3
loom_version                    = 1.16-SNAPSHOT
fabric_version                  = 0.152.0+26.2

# Mod Properties
mod_version                    = 1.0.0
maven_group                    = com.hlysine
archives_base_name             = create-fly-power-loader-fabric-26.2
